# For exploration online update
map_file: 'thor_magni_maps/1205_SC1B_map.png'
raw_dataset: 'DARKO'

# For splitting data into grid
radius: 0.3
step: 0.3
dataset_type: 'DARKO-MS2'

# For mean shift
convergence_thres_ms: 1e-5
group_distance_tolerance: 0.5
cluster_all: True
too_few_data_thres: 5
max_iter_ms: 100

# For EM
wind_num: 1
convergence_thres_em: 1e-5
max_iter_em: 100


# For update EM
decay_rate: 0.9
combine_thres: 1e-1