# For exploration online update
# raw_data_file: 'thor_magni_combine_add_time_all_dates_for_train_cliff_correct_ori/B.csv'
map_file: "thor_magni_maps/1205_SC1A_map.png"

# resolution
radius: 1
step: 1
x_min: 0
x_max: 1790
y_min: 650
y_max: 1417

# initial position
x_init: 50
y_init: 550
theta_init: 0

# hyperparameters
FREE: 255
OCCUPIED: 0
UNKNOWN: 128
fov_type: "cone"
fov_angle: 120
fov_radius: 200
w_dist: 0.45

# dataset_type: 'ART'
dataset_type: "OBSERVE"
# dataset_type: 'MAGNI'
